language: julia
sudo: false
matrix:
  include:
    - os: linux
      julia: 0.4
      env: TESTCMD="xvfb-run julia"
    - os: osx
      julia: 0.4
      env: TESTCMD="julia"
notifications:
    email: false
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - $TESTCMD -e 'Pkg.clone(pwd()); using BinDeps;
          println(BinDeps.debug("Gtk"));
          Pkg.test("Gtk"; coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Gtk"));
                Pkg.add("Coverage");
                using Coverage;
                Coveralls.submit(Coveralls.process_folder())'
