language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd());
          Pkg.build("Gtk");
          println(readall(Pkg.dir("Gtk/deps/deps.jl")));
          println(BinDeps.debug("Gtk"));
          Pkg.test("Gtk"; coverage=true)'
    - julia -e 'cd(Pkg.dir("Gtk"));
          Pkg.add("Coverage");
          using Coverage;
          Coveralls.submit(Coveralls.process_folder())'
